---
title: "Model Options"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model Options}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

A variety of model options need to be specified to ensure the projection components of afscOM works as expected.

| Paraemeter Name | Description | Dimensions | Default Value |
|-----------------|-------------|------------|---------------|
| `removals_input` | input units of removals (either “catch” is inputs are a total weight of catch, or “F” if an instantaneous fishing mortality rate) | - | “catch” |
| `fleet_apportionment` | Proportion of total catch allocated to each fishing fleet within each region | `[nyears, nfleets, nregions]` | `1/nfleets/nregions` |
| `simulate_observations` | Whether to simulate observations from the OM | - | TRUE |
| `recruit_apportionment` | Proportion of total recruits allocated to each region | `[nyears, nregions]` | `1/nregions` |    
| `recruit_apportionment_random` | Whether recruitment apportionment should be fixed at the values provided directly to the model, or whether to perform a random multinomial sample using the provided input as the probability of recruitment to each region. Sample size for multinomial sample is 30. | - | FALSE |
| `do_recruits_move` | Whether annual recruits are subject to movement in the year they recruit. | - | TRUE |

A helper function, `setup_model_options()` is provided to create a list of model options with the default values. This function does not set default values for observations parameters.
